name: cartsync
description: "Cart Sync - Collaborative family shopping list app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  dio: ^5.7.0
  dartz: ^0.10.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.2
  logger: ^2.5.0
  cupertino_icons: ^1.0.8
  stomp_dart_client: ^3.0.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  freezed: ^3.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
